### ISSUE TITLE
Implement add art object activity

### ISSUE THREAD

**Issue by genaforvena** [genaforvena/StreetArtView#26]
We need to have add object activity. Suggesting to style in the same way as instagram add picture. This activity need to be opened on floating button click.

**Comment by genaforvena** [comment]
Better idea - we need to remake detail art object view for it to provide editing functionality. User should be able to both modify existing art object (texts, images, everything). New objects should be created in the same fashion.

**Comment by sanovikov71** [comment]
I'll create adding functionality

**Comment by genaforvena** [comment]
For now as we'll have telegram chat bot we can just add a button to let users add artObjects and navigate them to this chat instead of creating new activity.
